package router

import (
	"github.com/gin-gonic/gin"
	"github.com/yypyyd/infinite-canvas/handler"
	"github.com/yypyyd/infinite-canvas/middleware"
)

func New() *gin.Engine {
	router := gin.New()
	router.Use(middleware.RequestObservability, gin.Recovery())
	router.RedirectTrailingSlash = false
	_ = router.SetTrustedProxies(nil)
	api := router.Group("/api")
	api.GET("/health", gin.WrapF(handler.Liveness))
	api.GET("/health/live", gin.WrapF(handler.Liveness))
	api.GET("/health/ready", gin.WrapF(handler.Readiness))
	api.POST("/auth/register", gin.WrapF(handler.Register))
	api.POST("/auth/email-code", gin.WrapF(handler.SendRegistrationEmailCode))
	api.POST("/auth/login", gin.WrapF(handler.Login))
	api.POST("/auth/logout", gin.WrapF(handler.Logout))
	api.GET("/auth/me", middleware.OptionalAuth, gin.WrapF(handler.CurrentUser))
	api.POST("/auth/profile", middleware.UserAuth, gin.WrapF(handler.UpdateProfile))
	api.POST("/auth/password", middleware.UserAuth, gin.WrapF(handler.ChangePassword))
	api.GET("/referrals", middleware.UserAuth, gin.WrapF(handler.ReferralDashboard))
	api.GET("/credit-logs", middleware.UserAuth, gin.WrapF(handler.UserCreditLogs))
	api.GET("/payments/config", middleware.UserAuth, gin.WrapF(handler.PaymentConfig))
	api.GET("/payments/orders", middleware.UserAuth, gin.WrapF(handler.PaymentOrders))
	api.POST("/payments/orders", middleware.UserAuth, gin.WrapF(handler.CreatePaymentOrder))
	api.GET("/payments/orders/:orderNo", middleware.UserAuth, func(c *gin.Context) { handler.PaymentOrder(c.Writer, c.Request, c.Param("orderNo")) })
	api.POST("/payments/exchanges", middleware.UserAuth, gin.WrapF(handler.ExchangeBalance))
	api.GET("/payments/notify", gin.WrapF(handler.PaymentNotify))
	api.GET("/payments/return", gin.WrapF(handler.PaymentReturn))
	api.GET("/generation-tasks", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.UserGenerationTasks))
	api.GET("/generation-tasks/recovery", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.RecoverUserGenerationTask))
	api.POST("/generation-tasks/recovery/acknowledge", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.AcknowledgeUserGenerationTaskRecoveries))
	api.GET("/workspace", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.UserWorkspace))
	api.POST("/workspace/changes", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.SaveUserWorkspace))
	api.POST("/workspace/files/upload-ticket", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.PrepareUserWorkspaceFileUpload))
	api.POST("/workspace/files/confirm", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.ConfirmUserWorkspaceFileUpload))
	api.POST("/workspace/files/:uploadId/cancel", middleware.UserAuth, middleware.OrganizationAuth, func(c *gin.Context) { handler.CancelUserWorkspaceFileUpload(c.Writer, c.Request, c.Param("uploadId")) })
	api.PUT("/workspace/files/:uploadId/content", middleware.UserAuth, middleware.OrganizationAuth, func(c *gin.Context) { handler.UploadLocalUserWorkspaceFile(c.Writer, c.Request, c.Param("uploadId")) })
	api.GET("/workspace/files/:storageKey", middleware.UserAuth, middleware.OrganizationAuth, func(c *gin.Context) {
		handler.UserWorkspaceFile(c.Writer, c.Request, c.Param("storageKey"))
	})
	api.HEAD("/workspace/files/:storageKey", middleware.UserAuth, middleware.OrganizationAuth, func(c *gin.Context) {
		handler.UserWorkspaceFile(c.Writer, c.Request, c.Param("storageKey"))
	})
	api.GET("/workspace/status", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.UserStorageStatus))
	api.GET("/preferences", middleware.UserAuth, gin.WrapF(handler.UserPreferences))
	api.POST("/preferences", middleware.UserAuth, gin.WrapF(handler.SaveUserPreferences))
	api.GET("/api-keys", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.UserAPIKeys))
	api.POST("/api-keys", middleware.UserAuth, middleware.OrganizationAuth, gin.WrapF(handler.CreateUserAPIKey))
	api.DELETE("/api-keys/:id", middleware.UserAuth, middleware.OrganizationAuth, func(c *gin.Context) { handler.DeleteUserAPIKey(c.Writer, c.Request, c.Param("id")) })
	commerce := api.Group("/commerce", middleware.UserAuth, middleware.OrganizationAuth)
	commerce.GET("/workspace", gin.WrapF(handler.CommerceWorkspace))
	commerce.POST("/organizations", gin.WrapF(handler.CreateOrganization))
	commerce.POST("/organizations/current", gin.WrapF(handler.UpdateOrganization))
	commerce.POST("/organization-credit-settings", gin.WrapF(handler.UpdateOrganizationCreditSettings))
	commerce.POST("/organization-credits/transfer", gin.WrapF(handler.TransferOrganizationCredits))
	commerce.POST("/organizations/switch", gin.WrapF(handler.SwitchOrganization))
	commerce.GET("/invitations", gin.WrapF(handler.PendingOrganizationInvitations))
	commerce.GET("/organization-invitations", gin.WrapF(handler.CurrentOrganizationInvitations))
	commerce.POST("/invitations", gin.WrapF(handler.InviteOrganizationMember))
	commerce.POST("/invitations/:id/accept", func(c *gin.Context) { handler.AcceptOrganizationInvitation(c.Writer, c.Request, c.Param("id")) })
	commerce.DELETE("/invitations/:id", func(c *gin.Context) { handler.RevokeOrganizationInvitation(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/members", gin.WrapF(handler.CommerceOrganizationMembers))
	commerce.POST("/members/:id", func(c *gin.Context) { handler.UpdateOrganizationMember(c.Writer, c.Request, c.Param("id")) })
	commerce.DELETE("/members/:id", func(c *gin.Context) { handler.RemoveOrganizationMember(c.Writer, c.Request, c.Param("id")) })
	commerce.POST("/members/:id/transfer-owner", func(c *gin.Context) { handler.TransferOrganizationOwnership(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/brands", gin.WrapF(handler.CommerceBrands))
	commerce.POST("/brands", gin.WrapF(handler.SaveCommerceBrand))
	commerce.DELETE("/brands/:id", func(c *gin.Context) { handler.DeleteCommerceBrand(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/products", gin.WrapF(handler.CommerceProducts))
	commerce.POST("/products", gin.WrapF(handler.SaveCommerceProduct))
	commerce.DELETE("/products/:id", func(c *gin.Context) { handler.DeleteCommerceProduct(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/products/:id/skus", func(c *gin.Context) { handler.CommerceProductSKUs(c.Writer, c.Request, c.Param("id")) })
	commerce.POST("/skus", gin.WrapF(handler.SaveCommerceProductSKU))
	commerce.DELETE("/skus/:id", func(c *gin.Context) { handler.DeleteCommerceProductSKU(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/production-templates", gin.WrapF(handler.CommerceProductionTemplates))
	commerce.POST("/production-templates", gin.WrapF(handler.SaveCommerceProductionTemplate))
	commerce.POST("/production-templates/:id/publish", func(c *gin.Context) { handler.PublishCommerceProductionTemplate(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/production-templates/:id/versions", func(c *gin.Context) { handler.CommerceProductionTemplateVersions(c.Writer, c.Request, c.Param("id")) })
	commerce.POST("/production-templates/preview", gin.WrapF(handler.PreviewCommerceProductionPrompt))
	commerce.GET("/production-delivery-specs", gin.WrapF(handler.CommerceProductionDeliverySpecs))
	commerce.POST("/production/image/preflight", gin.WrapF(handler.PreflightCommerceImageProduction))
	commerce.GET("/batch-jobs", gin.WrapF(handler.CommerceBatchJobs))
	commerce.POST("/batch-jobs", gin.WrapF(handler.CreateCommerceBatchJob))
	commerce.GET("/batch-jobs/:id", func(c *gin.Context) { handler.CommerceBatchJob(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/batch-jobs/:id/items", func(c *gin.Context) { handler.CommerceBatchItems(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/batch-jobs/:id/archive", func(c *gin.Context) { handler.DownloadCommerceBatchArchive(c.Writer, c.Request, c.Param("id")) })
	commerce.POST("/batch-jobs/:id/items/:itemId/review", func(c *gin.Context) {
		handler.ReviewCommerceBatchItem(c.Writer, c.Request, c.Param("id"), c.Param("itemId"))
	})
	commerce.POST("/batch-jobs/:id/items/:itemId/retry", func(c *gin.Context) {
		handler.RetryCommerceBatchItem(c.Writer, c.Request, c.Param("id"), c.Param("itemId"))
	})
	commerce.POST("/batch-jobs/:id/items/:itemId/primary", func(c *gin.Context) {
		handler.SetCommerceBatchItemPrimary(c.Writer, c.Request, c.Param("id"), c.Param("itemId"))
	})
	commerce.POST("/batch-jobs/:id/cancel", func(c *gin.Context) { handler.CancelCommerceBatchJob(c.Writer, c.Request, c.Param("id")) })
	commerce.POST("/batch-jobs/:id/retry", func(c *gin.Context) { handler.RetryCommerceBatchJob(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/video-projects", gin.WrapF(handler.CommerceVideoProjects))
	commerce.POST("/video-projects", gin.WrapF(handler.CreateCommerceVideoProject))
	commerce.GET("/video-projects/:id", func(c *gin.Context) { handler.CommerceVideoProject(c.Writer, c.Request, c.Param("id")) })
	commerce.POST("/video-projects/:id", func(c *gin.Context) { handler.SaveCommerceVideoProject(c.Writer, c.Request, c.Param("id")) })
	commerce.POST("/video-projects/:id/preflight", func(c *gin.Context) { handler.PreflightCommerceVideoProject(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/video-projects/:id/versions", func(c *gin.Context) { handler.CommerceVideoProjectVersions(c.Writer, c.Request, c.Param("id")) })
	commerce.POST("/video-projects/:id/versions", func(c *gin.Context) { handler.CreateCommerceVideoProjectVersion(c.Writer, c.Request, c.Param("id")) })
	commerce.GET("/video-projects/:id/versions/:version", func(c *gin.Context) {
		handler.CommerceVideoProjectVersion(c.Writer, c.Request, c.Param("id"), c.Param("version"))
	})
	commerce.GET("/audit-logs", gin.WrapF(handler.CommerceAuditLogs))
	api.GET("/settings", gin.WrapF(handler.Settings))
	api.GET("/check-in", middleware.UserAuth, gin.WrapF(handler.CheckInStatus))
	api.POST("/check-in", middleware.UserAuth, gin.WrapF(handler.CheckIn))
	api.POST("/redeem-codes/redeem", middleware.UserAuth, gin.WrapF(handler.RedeemCode))
	api.GET("/media/references/:id", func(c *gin.Context) {
		handler.ReferenceMedia(c.Writer, c.Request, c.Param("id"))
	})
	api.HEAD("/media/references/:id", func(c *gin.Context) {
		handler.ReferenceMedia(c.Writer, c.Request, c.Param("id"))
	})
	api.GET("/media/storage/:id", func(c *gin.Context) { handler.PublicLocalStorageReference(c.Writer, c.Request, c.Param("id")) })
	api.HEAD("/media/storage/:id", func(c *gin.Context) { handler.PublicLocalStorageReference(c.Writer, c.Request, c.Param("id")) })
	api.GET("/asset-files/:name", func(c *gin.Context) {
		handler.AssetFile(c.Writer, c.Request, c.Param("name"))
	})
	api.HEAD("/asset-files/:name", func(c *gin.Context) {
		handler.AssetFile(c.Writer, c.Request, c.Param("name"))
	})
	v1 := api.Group("/v1", middleware.APIAuth, middleware.OrganizationAuth)
	v1.GET("/models", gin.WrapF(handler.AIModels))
	v1.GET("/credits", gin.WrapF(handler.APICreditSummary))
	v1.GET("/pricing", gin.WrapF(handler.Pricing))
	v1.GET("/generation-tasks/recovery", gin.WrapF(handler.RecoverAPIGenerationTask))
	v1.POST("/images/generations", gin.WrapF(handler.AIImagesGenerations))
	v1.POST("/images/edits", gin.WrapF(handler.AIImagesEdits))
	v1.POST("/chat/completions", gin.WrapF(handler.AIChatCompletions))
	v1.POST("/audio/speech", gin.WrapF(handler.AIAudioSpeech))
	v1.POST("/videos", gin.WrapF(handler.AIVideos))
	v1.POST("/media/references", gin.WrapF(handler.UploadReferenceMedia))
	v1.POST("/agent/sessions", gin.WrapF(handler.CreateAgentSession))
	v1.POST("/agent/sessions/:id/messages", func(c *gin.Context) {
		handler.SubmitAgentMessage(c.Writer, c.Request, c.Param("id"))
	})
	v1.GET("/agent/runs/:id", func(c *gin.Context) {
		handler.GetAgentRun(c.Writer, c.Request, c.Param("id"))
	})
	v1.GET("/agent/runs/:id/diagnostics", func(c *gin.Context) {
		handler.GetAgentRunDiagnostics(c.Writer, c.Request, c.Param("id"))
	})
	v1.GET("/agent/metrics", gin.WrapF(handler.GetAgentMetrics))
	v1.POST("/agent/runs/:id/feedback", func(c *gin.Context) {
		handler.SubmitAgentFeedback(c.Writer, c.Request, c.Param("id"))
	})
	v1.GET("/agent/runs/:id/events", func(c *gin.Context) {
		handler.AgentRunEvents(c.Writer, c.Request, c.Param("id"))
	})
	v1.POST("/agent/runs/:id/tool-results", func(c *gin.Context) {
		handler.SubmitAgentToolResult(c.Writer, c.Request, c.Param("id"))
	})
	v1.GET("/agent/runs/:id/tool-results/:callId", func(c *gin.Context) {
		handler.GetAgentToolResultReceipt(c.Writer, c.Request, c.Param("id"), c.Param("callId"))
	})
	v1.POST("/agent/runs/:id/tool-claims", func(c *gin.Context) {
		handler.ClaimAgentToolExecution(c.Writer, c.Request, c.Param("id"))
	})
	v1.POST("/agent/runs/:id/confirmation", func(c *gin.Context) {
		handler.ConfirmAgentTool(c.Writer, c.Request, c.Param("id"))
	})
	v1.POST("/agent/runs/:id/cancel", func(c *gin.Context) {
		handler.CancelAgentRun(c.Writer, c.Request, c.Param("id"))
	})
	v1.POST("/agent/runs/:id/tool-reverts", func(c *gin.Context) {
		handler.RevertAgentTool(c.Writer, c.Request, c.Param("id"))
	})
	v1.POST("/agent/runs/:id/revert", func(c *gin.Context) {
		handler.RevertAgentRun(c.Writer, c.Request, c.Param("id"))
	})
	v1.POST("/agent/runs/:id/steps/:callId/retry", func(c *gin.Context) {
		handler.RetryAgentStep(c.Writer, c.Request, c.Param("id"), c.Param("callId"))
	})
	v1.GET("/videos/:id", func(c *gin.Context) {
		handler.AIVideo(c.Writer, c.Request, c.Param("id"))
	})
	v1.GET("/videos/:id/content", func(c *gin.Context) {
		handler.AIVideoContent(c.Writer, c.Request, c.Param("id"))
	})
	api.GET("/prompts", middleware.OptionalAuth, gin.WrapF(handler.Prompts))
	api.GET("/assets", middleware.OptionalAuth, gin.WrapF(handler.Assets))
	api.POST("/admin/login", gin.WrapF(handler.AdminLogin))

	admin := api.Group("/admin", middleware.AdminAuth)
	admin.GET("/users", gin.WrapF(handler.AdminUsers))
	admin.GET("/dashboard", gin.WrapF(handler.AdminDashboard))
	admin.GET("/operations/health", gin.WrapF(handler.AdminOperationsHealth))
	admin.GET("/operations/data-consistency", gin.WrapF(handler.AdminDataConsistency))
	admin.POST("/operations/data-consistency/repair", gin.WrapF(handler.AdminRepairDataConsistency))
	admin.GET("/generation-tasks", gin.WrapF(handler.AdminGenerationTasks))
	admin.POST("/users", gin.WrapF(handler.AdminSaveUser))
	admin.GET("/users/:id/pricing-discounts", func(c *gin.Context) {
		handler.AdminUserPricingDiscounts(c.Writer, c.Request, c.Param("id"))
	})
	admin.POST("/users/:id/pricing-discounts", func(c *gin.Context) {
		handler.AdminReplaceUserPricingDiscounts(c.Writer, c.Request, c.Param("id"))
	})
	admin.POST("/users/:id/credits", func(c *gin.Context) {
		handler.AdminAdjustUserCredits(c.Writer, c.Request, c.Param("id"))
	})
	admin.DELETE("/users/:id", func(c *gin.Context) {
		handler.AdminDeleteUser(c.Writer, c.Request, c.Param("id"))
	})
	admin.GET("/credit-logs", gin.WrapF(handler.AdminCreditLogs))
	admin.POST("/credit-logs", gin.WrapF(handler.AdminSaveCreditLog))
	admin.DELETE("/credit-logs/:id", func(c *gin.Context) {
		handler.AdminDeleteCreditLog(c.Writer, c.Request, c.Param("id"))
	})
	admin.GET("/redeem-codes", gin.WrapF(handler.AdminRedemptionCodes))
	admin.POST("/redeem-codes/generate", gin.WrapF(handler.AdminGenerateRedemptionCodes))
	admin.POST("/redeem-codes/batch-delete", gin.WrapF(handler.AdminDeleteRedemptionCodes))
	admin.DELETE("/redeem-codes/:id", func(c *gin.Context) {
		handler.AdminDeleteRedemptionCode(c.Writer, c.Request, c.Param("id"))
	})
	admin.GET("/settings", gin.WrapF(handler.AdminSettings))
	admin.POST("/settings", gin.WrapF(handler.AdminSaveSettings))
	admin.POST("/settings/channel-models", gin.WrapF(handler.AdminChannelModels))
	admin.POST("/settings/channel-test", gin.WrapF(handler.AdminTestChannelModel))
	admin.GET("/prompt-categories", gin.WrapF(handler.AdminPromptCategories))
	admin.POST("/prompt-categories/sync", gin.WrapF(handler.AdminSyncPromptCategories))
	admin.GET("/prompts", gin.WrapF(handler.AdminPrompts))
	admin.POST("/prompts", gin.WrapF(handler.AdminSavePrompt))
	admin.POST("/prompts/batch-delete", gin.WrapF(handler.AdminDeletePrompts))
	admin.DELETE("/prompts/:id", func(c *gin.Context) {
		handler.AdminDeletePrompt(c.Writer, c.Request, c.Param("id"))
	})
	admin.GET("/assets", gin.WrapF(handler.AdminAssets))
	admin.POST("/assets", gin.WrapF(handler.AdminSaveAsset))
	admin.POST("/asset-files", gin.WrapF(handler.AdminUploadAssetFile))
	admin.DELETE("/assets/:id", func(c *gin.Context) {
		handler.AdminDeleteAsset(c.Writer, c.Request, c.Param("id"))
	})

	router.NoRoute(middleware.NotFoundJSON)

	return router
}
